# Generated by Django 4.2.5 on 2023-09-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='nome',
            field=models.CharField(default='Visualizador', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.cargos'),
        ),
    ]
