# Generated by Django 4.2.5 on 2023-09-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_cargos_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos',
            name='nome',
        ),
    ]
