# Generated by Django 4.2.5 on 2023-09-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_remove_cargos_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='titulo',
            field=models.CharField(default='padrao', max_length=20),
            preserve_default=False,
        ),
    ]
