# Generated by Django 4.2.5 on 2023-09-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='cargo',
        ),
        migrations.DeleteModel(
            name='Cargos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
