# Generated by Django 4.2.5 on 2023-09-06 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PneusCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PneusMotoDianteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PneusMotoTraseiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVtCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVtMotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViaturasMotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=20, unique=True)),
                ('nome_moto', models.CharField(max_length=30)),
                ('odometro', models.IntegerField(max_length=6)),
                ('batalhao_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.batalhao')),
                ('pneu_dianteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.pneusmotodianteiro')),
                ('pneu_traseiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.pneusmototraseiro')),
                ('tipo_viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipovtmotos')),
            ],
        ),
        migrations.CreateModel(
            name='ViaturasCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=20, unique=True)),
                ('nome_carro', models.CharField(max_length=30)),
                ('odometro', models.IntegerField(max_length=6)),
                ('batalhao_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.batalhao')),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.pneuscarros')),
                ('tipo_viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipovtcarros')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosMotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pim', models.CharField(max_length=25, unique=True)),
                ('quantidade', models.IntegerField(max_length=2)),
                ('data', models.DateField(default=datetime.date.today)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.viaturasmotos')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pim', models.CharField(max_length=25, unique=True)),
                ('quantidade', models.IntegerField(max_length=2)),
                ('data', models.DateField(default=datetime.date.today)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.viaturascarros')),
            ],
        ),
    ]
