# Generated by Django 4.2.5 on 2023-09-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoscarros',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidosmotos',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='viaturascarros',
            name='odometro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='viaturasmotos',
            name='odometro',
            field=models.IntegerField(),
        ),
    ]
